name: Hawk
main: me.simplex.hawk.Hawk
version: 0.1.0
website: http://over9000.eu
author: simplex
description: Fly until the server laggs
permissions:
  hawk.*:
    description: allows the user to fly
    children:
      hawk.fly: true
  hawk.fly:
    default: op
    description: allows the user to fly